"""add fields to repetition_schedule

Revision ID: 3e0887a634c9
Revises: abb4f0b81d33
Create Date: 2025-09-29 21:54:15.572881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0887a634c9'
down_revision = 'abb4f0b81d33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('repetition_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repetitions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('efactor', sa.Float(), nullable=True))
        batch_op.alter_column('next_review_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['flashcard_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repetition_schedule', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('next_review_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('efactor')
        batch_op.drop_column('repetitions')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
