"""Add level field to Category model

Revision ID: 6a6f8e52f9f3
Revises: 3e0887a634c9
Create Date: 2025-11-03 11:50:23.803847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '6a6f8e52f9f3'
down_revision = '3e0887a634c9'
branch_labels = None
depends_on = None


def upgrade():
    op.add_column('categories', sa.Column('level', sa.String(length=5), nullable=True))

    # 1.2. Обновляем ВСЕ существующие строки, устанавливая значение по умолчанию 'USER'
    # Это устраняет ошибку NotNullViolation
    op.execute(text("UPDATE categories SET level = 'USER' WHERE level IS NULL;"))

    # 1.3. Изменяем колонку, чтобы установить ограничение NOT NULL
    op.alter_column('categories', 'level',
               existing_type=sa.String(length=5),
               nullable=False)
    # =========================================================

    # === 2. ИСПРАВЛЕНИЕ: repetition_schedule.next_review_date (по предупреждению) ===
    # Alembic также заметил проблему с next_review_date. Исправим ее.
    # Устанавливаем текущую дату для всех NULL значений.
    op.execute(text("UPDATE repetition_schedule SET next_review_date = CURRENT_DATE WHERE next_review_date IS NULL;"))

    # Убеждаемся, что колонка имеет правильный тип и NOT NULL
    with op.batch_alter_table('repetition_schedule', schema=None) as batch_op:
        batch_op.alter_column('next_review_date',
           existing_type=sa.DATE(),
           nullable=False,
           existing_server_default=sa.text('CURRENT_DATE')) # Или уберите existing_server_default, если он не нужен


def downgrade():
    op.drop_column('categories', 'level')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repetition_schedule', schema=None) as batch_op:
        batch_op.alter_column('next_review_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
